# Python Refresher

## Fundamentals of Python

- **Data Types and Variables:** Explores core data types (integers, floats, booleans, strings, complex numbers) and variable assignment.
- **Expressions and Branching:** Covers boolean logic (`and`, `or`, `not`, `is`) and controlling program flow with conditional statements (`if`, `elif`, `else`).
- **Code Structure:** Explains the role of indentation in defining blocks and managing line breaks.

## Working with Data

- **Lists:** Introduces lists as versatile containers for storing sequences of objects, demonstrating creation, manipulation, and iteration techniques.
- **Loops:** Delves into iterative execution using `for` and `while` loops, including the use of `else` blocks and control flow statements (`break`, `continue`).
- **The `range()` Function:**  Illustrates the generation of number sequences with `range()` and its application in loops.
- **User Input:** Shows how to take user input using the `input()` function.
- **File I/O:** Demonstrates how to read data from files and write data to files.

## Advanced Topics

- **Binary Data Formats:** Demonstrates how to handle data serialization and storage using Pickle and HDF5 formats.
- **Web APIs:**  Guides through interacting with external APIs (e.g., GitHub) using the `requests` library, fetching and processing data.
- **Database Interaction:** Covers establishing connections to SQLite databases, executing SQL queries, and managing result sets.

This notebook provides a solid foundation and refresher for Python programming, covering essential concepts and techniques for data manipulation, control flow, user interaction, file handling, and interaction with external resources.

## Fundamentals of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

### Data types

### Integers

Integer literals are created by any number without a decimal or complex component.

**Completed:** Pickle and HDF5 binary formats, GitHub API requests,
and SQLite database queries (create, insert, select with sorting/filtering).

In [2]:
# integers
a = 7
print("fggdgsgd" + str(a))

fggdgsgd7

### Floats

Float literals can be created by adding a decimal component to a number.

In [3]:
# float
x = 1
type(x)

int

### Boolean

Boolean can be defined by typing True/False without quotes

In [4]:
# boolean
b1 = True
b2 = False

type(b1)

bool

### Strings

String literals can be defined with any of single quotes ('), double quotes (") or triple quotes (''' or """). All give the same result with two important differences.

If you quote with single quotes, you do not have to escape double quotes and vice-versa.
If you quote with triple quotes, your string can span multiple lines.

In [7]:
# string
name1 = 'your name Wejdan'
type(name1)
name1

'your name Wejdan'

### Complex

Complex literals can be created by using the notation x + yj where x is the real component and y is the imaginary component.

In [8]:
#complex numbers: note the use of `j` to specify the imaginary part


j = 1.0 - 2.0j

j

(1-2j)

In [ ]:
x

In [9]:
print(x.real, x.imag)

1 0

### Variables

#### Definining

A variable in Python is defined through assignment. There is no concept of declaring a variable outside of that assignment.

In [10]:
tenth = 10
tenth

10

#### Dynamic Typing

In Python, while the value that a variable points to has a type, the variable itself has no strict type in its definition. You can re-use the same variable to point to an object of a different type. It may be helpful to think of variables as "labels" associated with objects.

In [11]:
ten = 10
ten

10

In [12]:
ten = 'ten'
ten

'ten'

#### Strong Typing

While Python allows you to be very flexible with your types, you must still be aware of what those types are. Certain operations will require certain types as arguments.

In [13]:
'Day ' +str(1)

'Day 1'

This behavior is different from some other loosely-typed languages. If you were to do the same thing in JavaScript, you would get a different result.

In Python, however, it is possible to change the type of an object through builtin functions.

### Simple Expressions

### Boolean Evaluation

Boolean expressions are created with the keywords and, or, not and is. For example:

In [14]:
True and False

False

In [15]:
True or False

True

In [16]:
not True

False

In [17]:
not False

True

In [18]:
True is True

True

In [19]:
True is False

False

In [20]:
'a' is 'a'

<>:1: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
/tmp/ipykernel_2443/4112465208.py:1: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  'a' is 'a'

True

### Branching (if / elif / else)

Python provides the if statement to allow branching based on conditions. Multiple elif checks can also be performed followed by an optional else clause. The if statement can be used with any evaluation of truthiness.

In [21]:
i = 1
if (i < 3):
    print('less than 3')
    if i<2:
        print("Fsdfsf")
elif i < 5:
    print('less than 5')
else:
    print('5 or more')

less than 3
Fsdfsf

## **Working with data**: Containers and Control flows

One of the great advantages of Python as a programming language is the ease with which it allows you to manipulate containers. Containers (or collections) are an integral part of the language and, as you’ll see, built in to the core of the language’s syntax. As a result, thinking in a Pythonic manner means thinking about containers.

### Lists

The first container type that we will look at is the list. A list represents an ordered, mutable collection of objects. You can mix and match any type of object in a list, add to it and remove from it at will.

Creating Empty Lists. To create an empty list, you can use empty square brackets or use the list() function with no arguments.

In [22]:
l = []
l

[]

In [23]:
l = list()
l

[]

Initializing Lists. You can initialize a list with content of any sort using the same square bracket notation. The list() function also takes an iterable as a single argument and returns a shallow copy of that iterable as a new list. A list is one such iterable as we’ll see soon, and we’ll see others later.

In [24]:
l1 = ["dsad", 'b', 'c']
l2 = ['a',6,4.0]

In [25]:

l1  + l2

['dsad', 'b', 'c', 'a', 6, 4.0]

In [26]:
l

[]

A Python string is also a sequence of characters and can be treated as an iterable over those characters. Combined with the list() function, a new list of the characters can easily be generated.

In [27]:
l=list("jkdfgkdgj")
l

['j', 'k', 'd', 'f', 'g', 'k', 'd', 'g', 'j']

Adding. You can append to a list very easily (add to the end) or insert at an arbitrary index.

In [28]:
l

['j', 'k', 'd', 'f', 'g', 'k', 'd', 'g', 'j']

Iterating. Iterating over a list is very simple. All iterables in Python allow access to elements using the for ... in statement. In this structure, each element in the iterable is sequentially assigned to the "loop variable" for a single pass of the loop, during which the enclosed block is executed.

In [29]:
for fg in l:
    print((fg))

j
k
d
f
g
k
d
g
j

### Loops

In general, statements are executed sequentially: The first statement in a function is executed first, followed by the second, and so on. There may be a situation when you need to execute a block of code several number of times.

Programming languages provide various control structures that allow for more complicated execution paths.

#### For loop

The for loop in Python is used to iterate over a sequence (list, tuple, string) or other iterable objects. Iterating over a sequence is called traversal.

Loop continues until we reach the last item in the sequence. The body of for loop is separated from the rest of the code using indentation.


<img src="Images/forLoop.jpg">

In [30]:
# Program to find the sum of all numbers stored in a list

# List of numbers
numbers = ["Fsdfsf","fsdfs","sdffsfs"]

# variable to store the sum
summ=''

# iterate over the list
for x in numbers:
    summ = summ+x

# Output: The sum is 48
print(summ)

Fsdfsffsdfssdffsfs

### for loop with else
A for loop can have an optional else block as well. The else part is executed if the items in the sequence used in for loop exhausts.

break statement can be used to stop a for loop. In such case, the else part is ignored.

Hence, a for loop's else part runs if no break occurs.

Here is an example to illustrate this.

In [31]:
digits = [0, 1, 5]

for sfdsf in [0,1,2,3]:
    if sfdsf == 3:
        break
else:
    print("No items left.")
print("Fsdfsfsf")

Fsdfsfsf

### While loop

The while loop in Python is used to iterate over a block of code as long as the test expression (condition) is true.

The while loop in Python:

- Executes a block of code repeatedly as long as a condition is true
- Useful when the number of iterations is unknown beforehand
- Checks the condition before each iteration
- Continues until the condition becomes false
- Uses indentation to define the loop body
- Considers any non-zero value as True, while None and 0 are False

In [32]:
# Program to add natural
# numbers upto
# sum = 1+2+3+...+n

# To take input from the user,
# n = int(input("Enter n: "))

n = 10

# initialize sum and counter
sum = 0
i = 1

while i <= n:
    sum = sum + i
    i = i+1    # update counter

# print the sum
print("The sum is", sum)

The sum is 55

### The range() function

Python's range() function:

- Generates a sequence of numbers
- Basic syntax: range(stop) - generates numbers from 0 to stop-1
- Extended syntax: range(start, stop, step)

- Step size defaults to 1 if not specified

- Memory-efficient: generates numbers on-the-go
- Use list() function to output all items at once

The following example will clarify this.

In [33]:
range(6)

range(0, 6)

In [34]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
print(list(range(8, 2,-2)))

[8, 6, 4]

In [36]:
print(list(range(2, 20, 5)))

[2, 7, 12, 17]

In [39]:
list(range(len(genre)-1,0,-2))

[3, 1]

**Completed:** Lists, list manipulation, for/while loops, range(),
break/continue, and user input/file I/O. Fixed an ordering bug where
`genre` was referenced before being defined.

We can use the range() function in for loops to iterate through a sequence of numbers. It can be combined with the len() function to iterate though a sequence using indexing. Here is an example.

In [38]:
# Program to iterate through a list using indexing

genre = ['pop', 'rock', 'jazz','sapna']

# iterate over the list using index
for i in range(len(genre)-1,0,-2):
    print("I like", genre[i])

I like sapna
I like rock

### Break and Continue Statement

- Alter normal loop flow
- Used to end iterations or loops without checking the test - expression

#### break statement:

- Terminates the loop containing it
- Program control moves to the statement after the loop
- In nested loops, terminates only the innermost loop

If break statement is inside a nested loop (loop inside another loop), break will terminate the innermost loop.

In [40]:
# Use of break statement inside loop

for val in "string":
    if val == "i":
        break
    print(val)

print("The end")

s
t
r
The end

In this program, we iterate through the "string" sequence. We check if the letter is "i", upon which we break from the loop. Hence, we see in our output that all the letters up till "i" gets printed. After that, the loop terminates.

### continue
The continue statement is used to skip the rest of the code inside a loop for the current iteration only. Loop does not terminate but continues on with the next iteration.

<img src="Images/continue-statement-flowchart.jpg">

In [41]:
# Program to show the use of continue statement inside loops

for val in "string":
    if val == "i":
        continue
    print(val)

print("The end")

s
t
r
n
g
The end

This program is same as the above example except the break statement has been replaced with continue.

We continue with the loop, if the string is "i", not executing the rest of the block. Hence, we see in our output that all the letters except "i" gets printed.

In [42]:
# Break continue example 2

print("Break example:")
for i in range(5):
    if i == 3:
        print("Breaking the loop")
        break
    print(i)

print("\nContinue example:")
# Example of continue
for i in range(5):
    if i == 2:
        print("Skipping 2")
        continue
    print(i)

print("\nNested loop break example:")
# Example of break in nested loops
for i in range(3):
    for j in range(3):
        if i == 1 and j == 1:
            print(f"Breaking inner loop at i={i}, j={j}")
            break
        print(f"i={i}, j={j}")

Break example:
0
1
2
Breaking the loop

Continue example:
0
1
Skipping 2
3
4

Nested loop break example:
i=0, j=0
i=0, j=1
i=0, j=2
i=1, j=0
Breaking inner loop at i=1, j=1
i=2, j=0
i=2, j=1
i=2, j=2

### Input string

In [43]:
# Program to take the input string from the user.

name = input("What is your name? ")
type(name)

What is your name? Wejdan

str

In [44]:
# Program to read integers from user

age = input("What is your age? ")
print ("Your age is: ", age)
type(age)

What is your age? 45
Your age is:  45

str

In [45]:
# Let's have one more example

name = input("What is your name? ")
print (" It was nice talking you " + name + "!")
age = input("Enter your age? ")
print("Hey, you are already " + age + " years old, " + name + "!")

What is your name? Wejdan
 It was nice talking you Wejdan!
Enter your age? 45
Hey, you are already 45 years old, Wejdan!

## **Advanced Topics**

### file Read Write operation with Pandas

In [46]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=4) # sets floating-point numbers to 4 decimal places

In [48]:
import pandas as pd

draft1 = pd.read_excel('ex1.xlsx')    # Supply the file name (path) to ex1

draft1.head(4)

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [49]:
draft2 = pd.read_table('test.tsv')  # Read a tsv into a DataFrame

draft2.head()

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [51]:
df = pd.read_excel('ex1.xlsx')
df

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [55]:
import pandas as pd
pd.read_excel('ex1.xlsx').to_csv('ex1.csv', index=False)

In [56]:
pd.read_table('ex1.csv', sep=',')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [57]:
pd.read_csv('ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [60]:
df =pd.read_csv('ex2.csv', names=['asdfdsfs','fsdf', 'b', 'c', 'sudh', 'message'])
type(df)

pandas.core.frame.DataFrame

In [61]:
!cat csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [62]:

parsed = pd.read_csv('csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [63]:
!cat ex4.csv
pd.read_csv('ex4.csv', skiprows=[0, 2, 3])

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [64]:
!cat ex5.csv
result = pd.read_csv('ex5.csv')
result
pd.isnull(result)

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [65]:
result = pd.read_csv('ex5.csv', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [66]:
draft3 = pd.read_excel('sample_sales_data.xlsx', sheet_name='Monthly Sales') # Name of sheet to read from

draft3.head(6)

,Date,Product,Quantity,Unit Price,Customer,Total Sales
0,2024-07-22 23:39:56.780,Widget B,31,98.83,Customer 2,3063.73
1,2024-07-23 23:39:56.780,Widget B,30,11.03,Customer 2,330.90
2,2024-07-24 23:39:56.780,Widget A,38,26.86,Customer 4,1020.68
3,2024-07-25 23:39:56.780,Widget C,16,80.37,Customer 3,1285.92
4,2024-07-26 23:39:56.780,Widget A,19,34.67,Customer 1,658.73
5,2024-07-27 23:39:56.780,Widget C,32,33.99,Customer 1,1087.68

In [67]:
import pandas as pd
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html"

BB_data = pd.read_html(url)         # Read data from the specified url

BB_data[0].iloc[:, 0:20].head(5)      # Check 5 rows (10 columns only)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,0.440,208.0,555.0,0.375,439.0,915.0,0.480,0.511,715.0,824.0
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,0.487,286.0,646.0,0.443,367.0,695.0,0.528,0.594,308.0,337.0
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,0.426,86.0,288.0,0.299,541.0,1183.0,0.457,0.455,546.0,654.0
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,0.488,120.0,339.0,0.354,504.0,940.0,0.536,0.535,375.0,528.0
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,0.434,196.0,572.0,0.343,394.0,788.0,0.500,0.506,344.0,398.0

In [68]:
titanic_train = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv",
                           sep=',')

In [69]:
titanic_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [70]:
titanic_train[["Name","Pclass"]].head()

                                                Name  Pclass
0                            Braund, Mr. Owen Harris       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                             Heikkinen, Miss. Laina       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                           Allen, Mr. William Henry       3

In [71]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [72]:
pd.options.display.max_rows = 10

In [73]:
result = pd.read_csv('ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [74]:
pd.read_csv('ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [75]:
chunk = pd.read_csv('ex6.csv', chunksize=1000)
chunk

Writing Data to Text Format

In [76]:
data = pd.read_csv('ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [77]:
data.to_csv('out.csv')
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [78]:
import sys
data.to_csv('out1.csv', sep='@')

In [79]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [80]:
data.to_csv('out2.csv', index=False, header=False)

In [81]:
data.to_csv('out3.csv', index=False, columns=['a', 'b', 'c'])

In [82]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('tseries.csv')
!cat tseries.csv

,0
2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

Working with Delimited Formats

In [83]:
import csv
f = open('ex7.csv')

reader = csv.reader(f)
reader

In [84]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [85]:
with open('ex7.csv') as f:
    lines = list(csv.reader(f))

In [86]:
header, values = lines[0], lines[1:]

In [87]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

### JSON Data

In [88]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [89]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [90]:
asjson = json.dumps(result)

In [91]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age','pets'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [92]:
!cat example.json # !cat is a bash command. find out what it does.

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [93]:
data = pd.read_json('example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [94]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

XML and HTML: Web Scraping

**Note:** This cell requires `fdic_failed_bank_list.html`, which was not included
in the provided datasets. Skipping this example — the read_html() concept is
understood from the markdown explanation above (parsing HTML tables into a
DataFrame), but it can't be executed here without the source file

In [95]:
tables = pd.read_html('fdic_failed_bank_list.html')
len(tables)
failures = tables[0]
failures.head()

/tmp/ipykernel_2443/958483958.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html('fdic_failed_bank_list.html')
/usr/local/lib/python3.12/dist-packages/pandas/io/html.py:661: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a filename than HTML or XML.

If you meant to use Beautiful Soup to parse the contents of a file on disk, then something has gone wrong. You should open the file first, using code like this:

    filehandle = open(your filename)

You can then feed the open filehandle into Beautiful Soup instead of using the filename.

However, if you want to parse some data that happens to look like a filename, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  soup = BeautifulSoup(udoc, features="html5lib", from_encoding=from_encoding)

ValueError: No tables found

In [96]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts()
#close_timestamps

NameError: name 'failures' is not defined

### Binary Data Formats

In [97]:
frame = pd.read_csv('ex1.csv')
frame
frame.to_pickle('frame_pickle')

In [98]:
pd.read_pickle('frame_pickle')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [99]:
!rm frame_pickle

Using HDF5 Format

In [100]:
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [101]:
store['obj1']

           a
0  -0.567842
1  -0.567017
2   0.852322
3   0.854732
4   1.650572
..       ...
95 -0.176218
96 -1.058837
97 -0.639866
98 -1.068769
99 -1.543435

[100 rows x 1 columns]

In [102]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()

In [103]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

/tmp/ipykernel_2443/1503106993.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  frame.to_hdf('mydata.h5', 'obj3', format='table')

          a
0 -0.567842
1 -0.567017
2  0.852322
3  0.854732
4  1.650572

### Data from Web APIs

In [104]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [105]:
data = resp.json()
data[2]['user']

{'login': 'goutamadwant',
 'id': 8672451,
 'node_id': 'MDQ6VXNlcjg2NzI0NTE=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/8672451?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/goutamadwant',
 'html_url': 'https://github.com/goutamadwant',
 'followers_url': 'https://api.github.com/users/goutamadwant/followers',
 'following_url': 'https://api.github.com/users/goutamadwant/following{/other_user}',
 'gists_url': 'https://api.github.com/users/goutamadwant/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/goutamadwant/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/goutamadwant/subscriptions',
 'organizations_url': 'https://api.github.com/users/goutamadwant/orgs',
 'repos_url': 'https://api.github.com/users/goutamadwant/repos',
 'events_url': 'https://api.github.com/users/goutamadwant/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/goutamadwant/received_events',
 'type': 'User',
 'user_view_type': 'public',
 'site_admin': False}

In [106]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

,number,title,labels,state
0,65916,Fix typo in OptionError messages,[],open
1,65915,BUG: Plotting with timezone-aware and normaliz...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
2,65913,BUG: Preserve None when replacing NaN in strin...,[],open
3,65912,STY: Update min versions pre-commit hook to al...,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open
4,65911,DEPR: by_blocks in tm.assert_frame_equal,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
...,...,...,...,...
25,65869,BUG: to_json not warning about deprecated epoc...,"[{'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3...",open
26,65868,BUG: missing deprecation warning about epoch t...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,65867,CLN: remove the deprecated is_sparse function,"[{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...",open
28,65866,BUG: to_json raising OverflowError for Period ...,[],open
29,65863,ENH: Support %N directive in strptime parsing ...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open

### Interacting with Databases

In [107]:
import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database4.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists test")
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata2.sqlite')
con.execute(query)
con.commit()

In [108]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [109]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [110]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [111]:
#!/usr/bin/python

import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database5.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists grades1")
# Create table as per requirement
db.execute("create table grades1(id int, name text, score int)")
#inserting values inside the created table
db.execute("insert into grades1(id, name, score) values(101, 'John',99 )")
db.execute("insert into grades1(id, name, score) values(102, 'Gary',90 )")
db.execute("insert into grades1(id, name, score) values(103, 'James', 80 )")
db.execute("insert into grades1(id, name, score) values(104, 'Cathy', 85 )")
db.execute("insert into grades1(id, name, score) values(105, 'Kris',95 )")

In [112]:
db.commit()

In [113]:
results = db.execute("select * from grades1 order by id")
for row in results:
    print((row))
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(103, 'James', 80)
(104, 'Cathy', 85)
(105, 'Kris', 95)
------------------------------------------------------------

In [114]:
results = db.execute("select * from grades1 where name = 'Gary' ")
for row in results: print(row)
print("-"* 60 )

(102, 'Gary', 90)
------------------------------------------------------------

In [115]:
results = db.execute("select * from grades1 where score >= 90 ")
for row in results:
    print(row)
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(105, 'Kris', 95)
------------------------------------------------------------

In [116]:
results = db.execute("select name, score from grades1 order by score desc ")
for row in results:
    print(row)
print("-" * 60 )

('John', 99)
('Kris', 95)
('Gary', 90)
('Cathy', 85)
('James', 80)
------------------------------------------------------------

In [117]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)
print("-" * 60 )

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)
------------------------------------------------------------

In [118]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)

In [119]:
from google.colab import files
uploaded = files.upload()

In [120]:
!git clone https://github.com/conslcan/Wejdan-Assignment2-Git-Colab.git

Cloning into 'Wejdan-Assignment2-Git-Colab'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 6 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), done.

In [121]:
%cd Wejdan-Assignment2-Git-Colab
!ls -la

/content/Wejdan-Assignment2-Git-Colab
total 380
drwxr-xr-x 3 root root   4096 Jun 20 15:17 .
drwxr-xr-x 1 root root   4096 Jun 20 15:16 ..
-rw-r--r-- 1 root root   1060 Jun 20 15:16 assignment2.ipynb
drwxr-xr-x 8 root root   4096 Jun 20 15:16 .git
-rw-r--r-- 1 root root     30 Jun 20 15:16 README.md
-rw-r--r-- 1 root root 367324 Jun 20 15:17 Wejdan_python_refresher.ipynb

In [123]:
!git config --global user.name "conslcan"
!git config --global user.email "conslcan@gmail.com"

In [124]:
!git add Wejdan_python_refresher.ipynb
!git commit -m "Complete Fundamentals of Python section: data types, booleans, conditionals"

[main 1662a6d] Complete Fundamentals of Python section: data types, booleans, conditionals
 1 file changed, 8315 insertions(+)
 create mode 100644 Wejdan_python_refresher.ipynb

In [126]:
!git add Wejdan_python_refresher.ipynb
!git commit -m "Complete Working with Data section: lists, loops, range(), file I/O"

[main 8011089] Complete Working with Data section: lists, loops, range(), file I/O
 1 file changed, 108 insertions(+)